### ISSUE TITLE
`make setup` fails on Mac

### ISSUE THREAD

**Issue by michielbdejong** [TheIdentitySelector/thiss-js#268]
Here are my logs from `make setup`:
```
[...]
8835 timing build:link:node_modules/nyc/node_modules/semver Completed in 11ms
8836 timing build:link:node_modules/nyc/node_modules/which Completed in 11ms
8837 timing build:link:node_modules/recast/node_modules/esprima Completed in 11ms
8838 timing build:link:node_modules/url-loader/node_modules/mime Completed in 11ms
8839 timing build:link:node_modules/webpack/node_modules/json5 Completed in 11ms
8840 timing build:link Completed in 17ms
8841 info run fibers@4.0.3 install node_modules/fibers node build.js || nodejs build.js
8842 info run node-sass@4.14.1 install node_modules/node-sass node scripts/install.js
8843 info run sharp@0.22.1 install node_modules/favicons/node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
8844 info run fsevents@1.2.13 install node_modules/watchpack-chokidar2/node_modules/fsevents node install.js
8845 info run fsevents@1.2.13 install node_modules/webpack-dev-server/node_modules/fsevents node install.js
8846 info run node-sass@4.14.1 install { code: 0, signal: null }
8847 timing build:run:install:node_modules/node-sass Completed in 815ms
8848 info run fsevents@1.2.13 install { code: 0, signal: null }
8849 timing build:run:install:node_modules/watchpack-chokidar2/node_modules/fsevents Completed in 1212ms
8850 info run fsevents@1.2.13 install { code: 0, signal: null }
8851 timing build:run:install:node_modules/webpack-dev-server/node_modules/fsevents Completed in 1210ms
8852 info run fibers@4.0.3 install { code: 127, signal: null }
8853 info run sharp@0.22.1 install { code: 1, signal: null }
8854 warn cleanup Failed to remove some directories [
8854 warn cleanup   [
8854 warn cleanup     '/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/favicons/node_modules/sharp',
8854 warn cleanup     [Error: ENOTEMPTY: directory not empty, rmdir '/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/favicons/node_modules/sharp'] {
8854 warn cleanup       errno: -66,
8854 warn cleanup       code: 'ENOTEMPTY',
8854 warn cleanup       syscall: 'rmdir',
8854 warn cleanup       path: '/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/favicons/node_modules/sharp'
8854 warn cleanup     }
8854 warn cleanup   ]
8854 warn cleanup ]
8855 timing reify:rollback:createSparse Completed in 5099ms
8856 timing reify:rollback:retireShallow Completed in 1ms
8857 timing command:install Completed in 178703ms
8858 verbose stack Error: command failed
8858 verbose stack     at ChildProcess.<anonymous> (/Users/michiel/.volta/tools/image/node/20.11.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
8858 verbose stack     at ChildProcess.emit (node:events:518:28)
8858 verbose stack     at maybeClose (node:internal/child_process:1105:16)
8858 verbose stack     at Socket.<anonymous> (node:internal/child_process:457:11)
8858 verbose stack     at Socket.emit (node:events:518:28)
8858 verbose stack     at Pipe.<anonymous> (node:net:337:12)
8859 verbose pkgid fibers@4.0.3
8860 verbose cwd /Users/michiel/gh/TheIdentitySelector/thiss-js
8861 verbose Darwin 23.4.0
8862 verbose node v20.11.0
8863 verbose npm  v10.2.4
8864 error code 127
8865 error path /Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/fibers
8866 error command failed
8867 error command sh -c node build.js || nodejs build.js
8868 error gyp info it worked if it ends with ok
8868 error gyp info using node-gyp@3.8.0
8868 error gyp info using node@20.11.0 | darwin | x64
8868 error gyp info spawn /Users/michiel/.pyenv/shims/python2
8868 error gyp info spawn args [
8868 error gyp info spawn args   '/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp/gyp/gyp_main.py',
8868 error gyp info spawn args   'binding.gyp',
8868 error gyp info spawn args   '-f',
8868 error gyp info spawn args   'make',
8868 error gyp info spawn args   '-I',
8868 error gyp info spawn args   '/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/fibers/build/config.gypi',
8868 error gyp info spawn args   '-I',
8868 error gyp info spawn args   '/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp/addon.gypi',
8868 error gyp info spawn args   '-I',
8868 error gyp info spawn args   '/Users/michiel/.node-gyp/20.11.0/include/node/common.gypi',
8868 error gyp info spawn args   '-Dlibrary=shared_library',
8868 error gyp info spawn args   '-Dvisibility=default',
8868 error gyp info spawn args   '-Dnode_root_dir=/Users/michiel/.node-gyp/20.11.0',
8868 error gyp info spawn args   '-Dnode_gyp_dir=/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp',
8868 error gyp info spawn args   '-Dnode_lib_file=/Users/michiel/.node-gyp/20.11.0/<(target_arch)/node.lib',
8868 error gyp info spawn args   '-Dmodule_root_dir=/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/fibers',
8868 error gyp info spawn args   '-Dnode_engine=v8',
8868 error gyp info spawn args   '--depth=.',
8868 error gyp info spawn args   '--no-parallel',
8868 error gyp info spawn args   '--generator-output',
8868 error gyp info spawn args   'build',
8868 error gyp info spawn args   '-Goutput_dir=.'
8868 error gyp info spawn args ]
8868 error Traceback (most recent call last):
8868 error   File "/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
8868 error     sys.exit(gyp.script_main())
8868 error   File "/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
8868 error     return main(sys.argv[1:])
8868 error   File "/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
8868 error     return gyp_main(args)
8868 error   File "/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
8868 error     options.duplicate_basename_check)
8868 error   File "/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
8868 error     params['parallel'], params['root_targets'])
8868 error   File "/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
8868 error     variables, includes, depth, check, True)
8868 error   File "/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
8868 error     includes, True, check)
8868 error   File "/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
8868 error     aux_data, includes, check)
8868 error   File "/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
8868 error     LoadOneBuildFile(include, data, aux_data, None, False, check),
8868 error   File "/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
8868 error     None)
8868 error   File "/Users/michiel/.node-gyp/20.11.0/include/node/common.gypi", line 1
8868 error     incremental linking
8868 error                       ^
8868 error SyntaxError: invalid syntax
8868 error gyp ERR! configure error 
8868 error gyp ERR! stack Error: `gyp` failed with exit code: 1
8868 error gyp ERR! stack     at ChildProcess.onCpExit (/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/node-gyp/lib/configure.js:345:16)
8868 error gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
8868 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
8868 error gyp ERR! System Darwin 23.4.0
8868 error gyp ERR! command "/Users/michiel/.volta/tools/image/node/20.11.0/bin/node" "/Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/.bin/node-gyp" "rebuild" "--release"
8868 error gyp ERR! cwd /Users/michiel/gh/TheIdentitySelector/thiss-js/node_modules/fibers
8868 error gyp ERR! node -v v20.11.0
8868 error gyp ERR! node-gyp -v v3.8.0
8868 error gyp ERR! not ok 
8868 error node-gyp exited with code: 1
8868 error Please make sure you are using a supported platform and node version. If you
8868 error would like to compile fibers on this machine please make sure you have setup your
8868 error build environment--
8868 error Windows + OS X instructions here: https://github.com/nodejs/node-gyp
8868 error Ubuntu users please run: `sudo apt-get install g++ build-essential`
8868 error RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
8868 error Alpine users please run: `sudo apk add python make g++`
8868 error sh: nodejs: command not found
8869 verbose exit 127
8870 timing npm Completed in 178888ms
8871 verbose unfinished npm timer reify 1712897235808
8872 verbose unfinished npm timer reify:build 1712897408122
8873 verbose unfinished npm timer build 1712897408125
8874 verbose unfinished npm timer build:deps 1712897408125
8875 verbose unfinished npm timer build:run:install 1712897408172
8876 verbose unfinished npm timer build:run:install:node_modules/fibers 1712897408172
8877 verbose unfinished npm timer build:run:install:node_modules/favicons/node_modules/sharp 1712897408192
8878 verbose code 127
8879 error A complete log of this run can be found in: /Users/michiel/.npm/_logs/2024-04-12T04_47_15_623Z-debug-0.log
```
I'm trying to work out what the underlying error is, seems to be related to the [fibers](https://www.npmjs.com/package/fibers) package.

**Comment by michielbdejong** [comment]
I tried to using `docker build -f ./Dockerfile.build .` instead

**Comment by enriquepablo** [comment]
This is obsolete, now using node 22
